#!/usr/bin/env bash
# OpenMuse cloud demo helper for GitHub Codespaces. See demo/CLOUD_DEMO.md.
#
#   demo/openmuse.sh env      write openmuse/.env for this Codespace (native Anthropic backend)
#   demo/openmuse.sh api      start the API on 127.0.0.1:8787
#   demo/openmuse.sh web      start the Expo web UI on :8081, pointed at the public API URL
#   demo/openmuse.sh public   make ports 8787 and 8081 public
#   demo/openmuse.sh private  make them private again
#   demo/openmuse.sh urls     print the forwarded URLs
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/openmuse"
API_PORT="${API_PORT:-8787}"
WEB_PORT="${WEB_PORT:-8081}"
MODEL="${MODEL:-anthropic/claude-sonnet-4-5}"

forwarded_url() {
  if [[ -n "${CODESPACE_NAME:-}" && -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]]; then
    echo "https://${CODESPACE_NAME}-$1.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  else
    echo "http://localhost:$1"
  fi
}
API_URL="$(forwarded_url "$API_PORT")"
WEB_URL="$(forwarded_url "$WEB_PORT")"

need() {
  if [[ -z "${!1:-}" ]]; then
    echo "error: $1 is not set. Add it as a Codespaces secret and rebuild/restart the Codespace." >&2
    exit 1
  fi
}

write_env() {
  need ANTHROPIC_API_KEY
  need CPK_INTELLIGENCE_API_KEY
  local worker_token
  worker_token="$(openssl rand -hex 32)"
  umask 077
  cat >"$APP/.env" <<EOF
# Generated by demo/openmuse.sh env. Secrets come from Codespaces secrets; do not commit.
WORKSPACE_MODE=sample
AGENT_BACKEND=model
MODEL=$MODEL
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
CPK_INTELLIGENCE_API_KEY=$CPK_INTELLIGENCE_API_KEY
PORT=$API_PORT
HOST=127.0.0.1
PUBLIC_API_URL=$API_URL
ALLOWED_ORIGINS=$WEB_URL,http://localhost:$WEB_PORT,http://127.0.0.1:$WEB_PORT
DATA_DIR=.openmuse
TASK_WORKER_ENABLED=true
COMPUTER_ENABLED=false
# Optional browser worker (demo/CLOUD_DEMO.md, step 6). Stays on loopback; never make 8790 public.
BROWSER_WORKER_URL=http://127.0.0.1:8790
WORKER_TOKEN=$worker_token
WORKER_DATA_DIR=.openmuse/browser-profiles
WORKER_HOST=127.0.0.1
EOF
  echo "wrote $APP/.env"
  echo "  MODEL=$MODEL (native Anthropic, no shim)"
  echo "  PUBLIC_API_URL=$API_URL"
  echo "  ALLOWED_ORIGINS includes $WEB_URL"
}

set_visibility() {
  need CODESPACE_NAME
  gh codespace ports visibility "$API_PORT:$1" "$WEB_PORT:$1" -c "$CODESPACE_NAME"
}

cd "$APP"
case "${1:-}" in
  env) write_env ;;
  api)
    [[ -f .env ]] || write_env
    exec pnpm dev
    ;;
  web) EXPO_PUBLIC_API_URL="$API_URL" exec pnpm dev:web ;;
  public) set_visibility public ;;
  private) set_visibility private ;;
  urls) printf 'web UI: %s\nAPI:    %s/api/health\n' "$WEB_URL" "$API_URL" ;;
  *)
    sed -n '2,10p' "$0"
    exit 1
    ;;
esac
